default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  pool: 5
  username: root
  password: password
  port: 3306
  host: db #docker-cmopose.ymlのdbserviceの名前


development:
  <<: *default
  database: sample_development

test:
  <<: *default
  database: sample_test

production:
  <<: *default
  port: <%= ENV['RDS_PORT'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>